routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('pages.home');
});*/

Route::get('/vue', function () {
    return view('welcome');
});

Route::get('/','HomeController@index');
Route::get('/home','HomeController@index');
Route::post('/gg', 'ItemController@gg');

Route::get('/contact', 'HomeController@contact');
Route::get('/about', 'HomeController@about');

//Route::get('/review','PostsController@show_review');
//Route::get('/write_a_review','PostsController@write_a_review')->middleware('auth');
/*Route::get('/offers','PostsController@offers');*/
/*Route::get('/share_a_food','ShareafoodController@share_a_food')->middleware('auth');*/
Route::get('/foodgraphy','PostsController@foodgraphy');
Route::get('/map','MapController@index');
Route::get('/item/all','ItemController@allitem');

Route::get('/owners/all','HomeController@owners');


Route::get('/restaurant/all','RestaurantController@allrestaurant');


Route::get('/offer/search','OfferController@offer_search')->name('offer.search');
Route::get('/shareafood/search','ShareafoodController@shareafood_search')->name('shareafood.search');
Route::get('/reviews/search','ReviewsController@reviews_search')->name('reviews.search');






Route::get('reviews/tag/{slug}', 'ReviewsController@getSingle')->name('reviews.single')/*->where('slug', '[\w\d\-\_]+')*/;
Route::get('offer/tag/{slug}', 'OfferController@getSingle')->name('offer.single')/*->where('slug', '[\w\d\-\_]+')*/;
Route::get('shareafood/tag/{slug}', 'ShareafoodController@getSingle')->name('shareafood.single')/*->where('slug', '[\w\d\-\_]+')*/;
Route::get('restaurant/tag/{slug}', 'RestaurantController@getSingle')->name('restaurant.single');
Route::get('item/tag/{slug}', 'ItemController@getSingle')->name('item.single');


/*
Route::group(['middleware' => ['auth']], function () {



});*/

Route::resource('post','PostsController');
Route::resource('restaurant','RestaurantController');
Route::resource('item','ItemController');
Route::resource('shareafood','ShareafoodController');
Route::resource('reviews','ReviewsController');
Route::resource('area','AreaController');
Route::resource('offer','OfferController');
Route::resource('users','UserController');

Route::resource('reviewcomments','ReviewcommentController');
Route::resource('offercomments','OffercommentController');
Route::resource('shareafoodcomments','ShareafoodcommentController');


//Route::post('reviews/{slug}', ['as' => 'reviews.single', 'uses' => 'ReviewsController@store'])->where('slug', '[\w\d\-\_]+');




/*
Route::get('/admin_review','AdminController@show_review');
Route::get('/admin_write_a_review','AdminController@write_a_review');
Route::get('/admin_offers','AdminController@offers');
Route::get('/admin_share_a_food','AdminController@share_a_food');
Route::get('/admin_foodgraphy','AdminController@foodgraphy');
Route::get('/admin_home','AdminController@index');*/
Route::get('/admin_create','AdminController@create_pages');




Auth::routes();

/*Route::prefix('admin')->group(function (){
    Route::get('/login','/Auth/AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login','/Auth/AdminLoginController@login')->name('admin.login.submit');
    Route::get('/','AdminController@index')->name('admin.dashboard');

});*/
/*Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');


});*/
Route::post('/get_restaurant_info', 'RestaurantController@get_restaurants')->name('get_restaurants');
Route::post('/get_all_restaurant', 'RestaurantController@get_all_restaurant')->name('get_all_restaurant');
Route::post('/all_restaurants', 'RestaurantController@all_restaurant')->name('all_restaurant');
Route::post('/get_items', 'ItemController@get_items')->name('get_items');
Route::post('/get_area', 'AreaController@get_areas')->name('get_areas');
Route::post('/all_area', 'AreaController@all_areas')->name('all_areas');
Route::post('/get_restaurant_infos', 'RestaurantController@get_restaurant_info')->name('get_restaurant_infos');
//Route::get('/home', 'HomeController@index')->name('home');



/*Route::get('login/facebook', 'Auth\LoginController@redirectToProvider');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');*/

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password','featured_img','user_type'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function restaurant(){
        return $this->hasOne('App\restaurant');

    }


}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Gate;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {


        $this->middleware('auth');

    }


    public function index()
    {
        $users = User::all();

        return view('users.index')->withusers($users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::find($id);
        return view('users.show')->withuser($user);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
       // dd($user);
        return view('users.edit')->withuser($user);

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::find($id);
        $user->user_type= $request->input('user_type');

        $user->save();

        return redirect()->route('users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/users/create.blade.php
@extends('main')

@section('content')

    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1>Write a review</h1>
            <hr>
            <form method="POST" action="{{ route('reviews.store') }}">
                <div class="form-group">
                    <label name="reviewer_name">Reviewer:</label>
                    <input id="reviewer_name" name="reviewer_name" class="form-control">
                </div>
                <div class="form-group">
                    <label name="restaurant_name">Restaurant name:</label>
                    <select name="restaurant_name" id="restaurant_name" class="form-control">
                        <option value=""> -- Select One --</option>
                        @foreach ($x as $restaurant_name)
                            <option value="{{ $restaurant_name->id }}">{{ $restaurant_name->restaurant_name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label name="area_name">Restaurant area:</label>
                    <select name="area_name" id="area_name" class="form-control">
                        <option value=""> -- Select One --</option>
                        @foreach ($y as $area_name)
                            <option value="{{ $area_name->id }}">{{ $area_name->area_name }}</option>
                        @endforeach
                    </select>
                </div>

                <div class="form-group">
                    <label name="item_name">item name:</label>
                    <select name="item_name" id="restaurant_name" class="form-control">
                        <option value=""> -- Select One --</option>
                        @foreach ($z as $item_name)
                            <option value="{{ $item_name->id }}">{{ $item_name->item_name }}</option>
                        @endforeach
                    </select>
                </div>
               {{-- <div class="form-group">
                    <label name="restaurant_name">Place:</label>
                    <input id="place" name="place" class="form-control">
                </div>
                <div class="form-group">
                    <label name="restaurant_name">Name of food:</label>
                    <input id="name_of_food" name="name_of_food" class="form-control">
                </div>--}}
                <div class="form-group">
                    <label name="restaurant_name">rating:</label>
                    <input id="rating" name="rating" class="form-control">
                </div>
                <div class="form-group">
                    <label name="address">comment:</label>
                    <textarea id="comment" name="comment" rows="10" class="form-control"></textarea>
                </div>
                <div class="form-group">
                    <label for="exampleInputFile">File input</label>
                    <input type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
                    <small id="fileHelp" class="form-text text-muted"></small>
                </div>
                <input type="submit" value="give review" class="btn btn-success btn-lg btn-block">
                <input type="hidden" name="_token" value="{{ Session::token() }}">
            </form>
        </div>
    </div>﻿

    @endsection

resources/views/users/edit.blade.php
@extends('main')

@section('content')

    <form method="POST" action="{{ route('users.update', $user->id) }}">
        <div class="form-group">

            <div class="f-row">
                <label name="user_type">user role:</label>
                <select name="user_type" id="user_type" class="form-control">
                    <option value=""> -- Select One --</option>

                        <option value="superadmin">Superadmin</option>
                    <option value="restaurantmoderator">Restaurant Moderator</option>
                    <option value="user">User</option>




                </select>
            </div>


{{--
            <textarea type="text" class="form-control input-lg" id="user_type" name="user_type" rows="1" style="resize:none;">{{ $user->user_type }}</textarea>
--}}

  {{-- <div class="form-group">
            <label for="address">address:</label>
            <textarea type="text" class="form-control input-lg" id="address" name="address" rows="10">{{ $restaurant->address }}</textarea>
        </div>

        <div class="col-md-4">
            <div class="well">
                <dl class="dl-horizontal">
                    <dt>Created at:</dt>
                    <dd>{{ date('M j, Y h:i:sa', strtotime($restaurant->created_at)) }}</dd>
                </dl>

                <dl class="dl-horizontal">
                    <dt>Last updated:</dt>
                    <dd>{{ date('M j, Y h:i:sa', strtotime($restaurant->updated_at)) }}</dd>
                </dl>
                <hr>--}}
                <div class="row">
                  {{--  <div class="col-sm-6">
                        <a href="{{ route('restaurant.show', $restaurant->id) }}" class="btn btn-danger btn-block">Back</a>
                    </div>--}}
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-success btn-block">Save</button>
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                        {{ method_field('PUT') }}

                    </div>
                </div>
         {{--   </div>
        </div>--}}

    </form>﻿
@endsection

resources/views/users/index.blade.php
@extends('main')

@section('content')

    <div class="row">
       <div class="col-md-10">

           <h1>all users</h1>

       </div>
      {{--  <div class="col-md-2">

            <a href="{{ route('users.create') }}" class="btn btn-primary btn-block">Give a review</a>

        </div>--}}

<div class="row">
    <div class="col-md-12">
        <table class="table" id="users">

            <thead>
            <th>user name</th>
            <th>email</th>
            <th>user role</th>
            <th>edit role</th>


            </thead>
<tbody>
  @foreach($users as $user)
<tr>
    <td>{{$user->name}}</td>
    <td>{{$user->email}}</td>
    <td>{{$user->user_type}}</td>


          <td>
    <div class="col-sm-4">
        <a href="{{ route('users.edit', $user->id) }}" class="btn btn-success">Edit</a>
    </div>

        ﻿</td>
    {{--<td>{{str_limit($restaurant->address, 20)}}</td>
    <td>{{date('M j, Y',strtotime($restaurant->created_at))}}</td>
    <td>  <div class="row">
            <div class="col-sm-4">
                <a href="{{ route('restaurant.show', $restaurant->id) }}" class="btn btn-primary btn-block">Show</a>
            </div>
            <div class="col-sm-4">
                <a href="{{ route('restaurant.edit', $restaurant->id) }}" class="btn btn-primary btn-block">Edit</a>
            </div>
            <div class="col-sm-4">
                --}}{{--   <a href="{{ route('restaurant.destroy', $restaurant->id) }}" class="btn btn-danger btn-block">Delete</a>--}}{{--
                <form method="POST" action="{{ route('restaurant.destroy', $restaurant->id) }}">
                    <input type="submit" value="Delete" class="btn btn-danger btn-block">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                    {{ method_field('DELETE') }}
                </form>﻿
            </div>
        </div>﻿</td>--}}
</tr>
@endforeach

</tbody>
        </table>


    </div>

</div>

    </div>﻿

    @endsection

@section('page_js')
    <script>
        $(function () {
            var table = $('#users').DataTable(
                {
                    "pageLength": 50
                }
            )
        })

    </script>
@endsection

resources/views/users/show.blade.php
@extends('main')

@section('content')

    <div class="row">
        <div class="col-md-8 ">
            <h1>{{$user->name}}</h1>
            <p class="form-control">{{$user->user_role}} </p>
        </div>
    </div>﻿


        <div class="row">
            <div class="col-sm-4">
                <a href="{{ route('users.edit', $user->id) }}" class="btn btn-primary btn-block">Edit</a>
            </div>
          {{--  <div class="col-sm-4">
             --}}{{--   <a href="{{ route('restaurant.destroy', $restaurant->id) }}" class="btn btn-danger btn-block">Delete</a>--}}{{--
                <form method="POST" action="{{ route('restaurant.destroy', $restaurant->id) }}">
                    <input type="submit" value="Delete" class="btn btn-danger btn-block">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                    {{ method_field('DELETE') }}
                </form>﻿
            </div>--}}
        </div>﻿







    @endsection