routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('pages.home');
});*/

Route::get('/vue', function () {
    return view('welcome');
});

Route::get('/','HomeController@index');
Route::get('/home','HomeController@index');
Route::post('/gg', 'ItemController@gg');

Route::get('/contact', 'HomeController@contact');
Route::get('/about', 'HomeController@about');

//Route::get('/review','PostsController@show_review');
//Route::get('/write_a_review','PostsController@write_a_review')->middleware('auth');
/*Route::get('/offers','PostsController@offers');*/
/*Route::get('/share_a_food','ShareafoodController@share_a_food')->middleware('auth');*/
Route::get('/foodgraphy','PostsController@foodgraphy');
Route::get('/map','MapController@index');
Route::get('/item/all','ItemController@allitem');

Route::get('/owners/all','HomeController@owners');


Route::get('/restaurant/all','RestaurantController@allrestaurant');


Route::get('/offer/search','OfferController@offer_search')->name('offer.search');
Route::get('/shareafood/search','ShareafoodController@shareafood_search')->name('shareafood.search');
Route::get('/reviews/search','ReviewsController@reviews_search')->name('reviews.search');






Route::get('reviews/tag/{slug}', 'ReviewsController@getSingle')->name('reviews.single')/*->where('slug', '[\w\d\-\_]+')*/;
Route::get('offer/tag/{slug}', 'OfferController@getSingle')->name('offer.single')/*->where('slug', '[\w\d\-\_]+')*/;
Route::get('shareafood/tag/{slug}', 'ShareafoodController@getSingle')->name('shareafood.single')/*->where('slug', '[\w\d\-\_]+')*/;
Route::get('restaurant/tag/{slug}', 'RestaurantController@getSingle')->name('restaurant.single');
Route::get('item/tag/{slug}', 'ItemController@getSingle')->name('item.single');


/*
Route::group(['middleware' => ['auth']], function () {



});*/

Route::resource('post','PostsController');
Route::resource('restaurant','RestaurantController');
Route::resource('item','ItemController');
Route::resource('shareafood','ShareafoodController');
Route::resource('reviews','ReviewsController');
Route::resource('area','AreaController');
Route::resource('offer','OfferController');
Route::resource('users','UserController');

Route::resource('reviewcomments','ReviewcommentController');
Route::resource('offercomments','OffercommentController');
Route::resource('shareafoodcomments','ShareafoodcommentController');


//Route::post('reviews/{slug}', ['as' => 'reviews.single', 'uses' => 'ReviewsController@store'])->where('slug', '[\w\d\-\_]+');




/*
Route::get('/admin_review','AdminController@show_review');
Route::get('/admin_write_a_review','AdminController@write_a_review');
Route::get('/admin_offers','AdminController@offers');
Route::get('/admin_share_a_food','AdminController@share_a_food');
Route::get('/admin_foodgraphy','AdminController@foodgraphy');
Route::get('/admin_home','AdminController@index');*/
Route::get('/admin_create','AdminController@create_pages');




Auth::routes();

/*Route::prefix('admin')->group(function (){
    Route::get('/login','/Auth/AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login','/Auth/AdminLoginController@login')->name('admin.login.submit');
    Route::get('/','AdminController@index')->name('admin.dashboard');

});*/
/*Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');


});*/
Route::post('/get_restaurant_info', 'RestaurantController@get_restaurants')->name('get_restaurants');
Route::post('/get_all_restaurant', 'RestaurantController@get_all_restaurant')->name('get_all_restaurant');
Route::post('/all_restaurants', 'RestaurantController@all_restaurant')->name('all_restaurant');
Route::post('/get_items', 'ItemController@get_items')->name('get_items');
Route::post('/get_area', 'AreaController@get_areas')->name('get_areas');
Route::post('/all_area', 'AreaController@all_areas')->name('all_areas');
Route::post('/get_restaurant_infos', 'RestaurantController@get_restaurant_info')->name('get_restaurant_infos');
//Route::get('/home', 'HomeController@index')->name('home');



/*Route::get('login/facebook', 'Auth\LoginController@redirectToProvider');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');*/

app/Area.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Area extends Model
{
    public function restaurant(){

        return $this->hasMany('App\restaurant');
    }
     public function restaurants(){

         return $this->belongsToMany('App\restaurant');
     }

    public function shareafood(){

        return $this->hasMany('App\Shareafood');
    }

    public function offer(){

        return $this->hasMany('App\Offer');
    }
}

app/Http/Controllers/AreaController.php
<?php

namespace App\Http\Controllers;

use App\Area;
use Illuminate\Http\Request;


class AreaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth',['except' => ['index','show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $area = Area::all();
        return view('area.index')->witharea($area);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {    $x = Area::all();


        return view("area.create")->withx($x);
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, array(
            'area_name'         => 'required|max:255',

        ));


        $area = new Area();
        $area->area_name =$request->area_name;

        $area->save();
        session()->flash('success','It has been saved successfully!');
        return redirect()->route('area.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Area  $area
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $area = Area::find($id);
        return view('area.show')->witharea($area);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Area  $area
     * @return \Illuminate\Http\Response
     */
    public function edit(Area $area)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Area  $area
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Area $area)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Area  $area
     * @return \Illuminate\Http\Response
     */
    public function destroy(Area $area)
    {
        //
    }

    public function get_areas(Request $request){
//        dd($request);
        $areas = Area::all()->pluck('area_name','id')->toArray();
        return response()->json([json_encode([$areas])]);
    }

    public function all_areas(Request $request){
//        dd($request);
        $areas = Area::with(['Offer.Item','restaurant.Item'])->where('id',$request->id)->get()->toArray();
        return response()->json([json_encode([$areas])]);
    }
}

resources/views/area/create.blade.php
@extends('main')

@section('content')
    <div class="row">
        <!--content-->
        <section class="content center full-width">
            <div class="modal container">
                <form  method="POST" action="{{ route('area.store') }}" {{--name="contactform" id="contactform"--}}>
                    <h1 class="center">Add an area</h1>
                    <div id="message" class="alert alert-danger"></div>
                    <div class="f-row">
                        <label name="reviewer_name">Area Name:</label>
                        <input type="text" id="area_name" name="area_name" class="form-control" required="">
                    </div>


                    <div class="f-row bwrap">
                        <input type="submit" value="Add an Area" />
                    </div>
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                </form>
            </div>
        </section>
        <!--//content-->
    </div>


    @endsection

{{--
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h1>Write a review</h1>
        <hr>
        <form method="POST" action="{{ route('area.store') }}">
            <div class="form-group">
                <label name="reviewer_name">Area Name:</label>
                <input id="area_name" name="area_name" class="form-control">
            </div>

            <input type="submit" value="Submit" class="btn btn-success btn-lg btn-block">
            <input type="hidden" name="_token" value="{{ Session::token() }}">
        </form>
    </div>
</div>﻿--}}

resources/views/area/edit.blade.php
@extends('main')

@section('content')

    <form method="POST" action="{{ route('restaurant.update', $restaurant->id) }}">
        <div class="form-group">
            <label for="restaurant_name">restaurant_name:</label>
            <textarea type="text" class="form-control input-lg" id="restaurant_name" name="restaurant_name" rows="1" style="resize:none;">{{ $restaurant->restaurant_name }}</textarea>
        </div>
        <div class="form-group">
            <label for="address">address:</label>
            <textarea type="text" class="form-control input-lg" id="address" name="address" rows="10">{{ $restaurant->address }}</textarea>
        </div>

        <div class="col-md-4">
            <div class="well">
                <dl class="dl-horizontal">
                    <dt>Created at:</dt>
                    <dd>{{ date('M j, Y h:i:sa', strtotime($restaurant->created_at)) }}</dd>
                </dl>

                <dl class="dl-horizontal">
                    <dt>Last updated:</dt>
                    <dd>{{ date('M j, Y h:i:sa', strtotime($restaurant->updated_at)) }}</dd>
                </dl>
                <hr>
                <div class="row">
                    <div class="col-sm-6">
                        <a href="{{ route('restaurant.show', $restaurant->id) }}" class="btn btn-danger btn-block">Back</a>
                    </div>
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-success btn-block">Save</button>
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
        {{ method_field('PUT') }}

                    </div>
                </div>
            </div>
        </div>

    </form>﻿
    @endsection

resources/views/area/index.blade.php
@extends('main')

@section('content')

    <div class="row">
       <div class="col-md-10">

           <h1>all post</h1>

       </div>
        <div class="col-md-2">

            <a href="{{ route('area.create') }}" class="button">create an area</a>

        </div>

<div class="row">
    <div class="col-md-12">
        <table class="table" id="areas">

            <thead>
{{--
            <th>#</th>
--}}
            <th>area name</th>


            </thead>
<tbody>
  @foreach($area as $areas)
<tr>
{{--
    <td>{{$areas->id}}</td>
--}}
    <td>{{$areas->area_name}}</td>



    {{--<td>{{str_limit($restaurant->address, 20)}}</td>
    <td>{{date('M j, Y',strtotime($restaurant->created_at))}}</td>
    <td>  <div class="row">
            <div class="col-sm-4">
                <a href="{{ route('restaurant.show', $restaurant->id) }}" class="btn btn-primary btn-block">Show</a>
            </div>
            <div class="col-sm-4">
                <a href="{{ route('restaurant.edit', $restaurant->id) }}" class="btn btn-primary btn-block">Edit</a>
            </div>
            <div class="col-sm-4">
                --}}{{--   <a href="{{ route('restaurant.destroy', $restaurant->id) }}" class="btn btn-danger btn-block">Delete</a>--}}{{--
                <form method="POST" action="{{ route('restaurant.destroy', $restaurant->id) }}">
                    <input type="submit" value="Delete" class="btn btn-danger btn-block">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                    {{ method_field('DELETE') }}
                </form>﻿
            </div>
        </div>﻿</td>--}}
</tr>
@endforeach

</tbody>
        </table>


    </div>

</div>

    </div>﻿

    @endsection


@section('page_js')
    <script>
        $(function () {
            var table = $('#areas').DataTable(
                {
                    "pageLength": 50
                }
            )
        })

    </script>
@endsection

resources/views/area/show.blade.php
@extends('main')

@section('content')

    <div class="row">
        <div class="col-md-8 ">
            <h1>{{$area->area_name}}</h1>

        </div>
    </div>﻿


  {{--      <div class="row">
            <div class="col-sm-4">
                <a href="{{ route('area.edit', $area->id) }}" class="btn btn-primary btn-block">Edit</a>
            </div>
            <div class="col-sm-4">
             --}}{{--   <a href="{{ route('restaurant.destroy', $restaurant->id) }}" class="btn btn-danger btn-block">Delete</a>--}}{{--
                <form method="POST" action="{{ route('area.destroy', $area->id) }}">
                    <input type="submit" value="Delete" class="btn btn-danger btn-block">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                    {{ method_field('DELETE') }}
                </form>﻿
            </div>
        </div>﻿
--}}






    @endsection