routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('pages.home');
});*/

Route::get('/vue', function () {
    return view('welcome');
});

Route::get('/','HomeController@index');
Route::get('/home','HomeController@index');
Route::post('/gg', 'ItemController@gg');

Route::get('/contact', 'HomeController@contact');
Route::get('/about', 'HomeController@about');

//Route::get('/review','PostsController@show_review');
//Route::get('/write_a_review','PostsController@write_a_review')->middleware('auth');
/*Route::get('/offers','PostsController@offers');*/
/*Route::get('/share_a_food','ShareafoodController@share_a_food')->middleware('auth');*/
Route::get('/foodgraphy','PostsController@foodgraphy');
Route::get('/map','MapController@index');
Route::get('/item/all','ItemController@allitem');

Route::get('/owners/all','HomeController@owners');


Route::get('/restaurant/all','RestaurantController@allrestaurant');


Route::get('/offer/search','OfferController@offer_search')->name('offer.search');
Route::get('/shareafood/search','ShareafoodController@shareafood_search')->name('shareafood.search');
Route::get('/reviews/search','ReviewsController@reviews_search')->name('reviews.search');






Route::get('reviews/tag/{slug}', 'ReviewsController@getSingle')->name('reviews.single')/*->where('slug', '[\w\d\-\_]+')*/;
Route::get('offer/tag/{slug}', 'OfferController@getSingle')->name('offer.single')/*->where('slug', '[\w\d\-\_]+')*/;
Route::get('shareafood/tag/{slug}', 'ShareafoodController@getSingle')->name('shareafood.single')/*->where('slug', '[\w\d\-\_]+')*/;
Route::get('restaurant/tag/{slug}', 'RestaurantController@getSingle')->name('restaurant.single');
Route::get('item/tag/{slug}', 'ItemController@getSingle')->name('item.single');


/*
Route::group(['middleware' => ['auth']], function () {



});*/

Route::resource('post','PostsController');
Route::resource('restaurant','RestaurantController');
Route::resource('item','ItemController');
Route::resource('shareafood','ShareafoodController');
Route::resource('reviews','ReviewsController');
Route::resource('area','AreaController');
Route::resource('offer','OfferController');
Route::resource('users','UserController');

Route::resource('reviewcomments','ReviewcommentController');
Route::resource('offercomments','OffercommentController');
Route::resource('shareafoodcomments','ShareafoodcommentController');


//Route::post('reviews/{slug}', ['as' => 'reviews.single', 'uses' => 'ReviewsController@store'])->where('slug', '[\w\d\-\_]+');




/*
Route::get('/admin_review','AdminController@show_review');
Route::get('/admin_write_a_review','AdminController@write_a_review');
Route::get('/admin_offers','AdminController@offers');
Route::get('/admin_share_a_food','AdminController@share_a_food');
Route::get('/admin_foodgraphy','AdminController@foodgraphy');
Route::get('/admin_home','AdminController@index');*/
Route::get('/admin_create','AdminController@create_pages');




Auth::routes();

/*Route::prefix('admin')->group(function (){
    Route::get('/login','/Auth/AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login','/Auth/AdminLoginController@login')->name('admin.login.submit');
    Route::get('/','AdminController@index')->name('admin.dashboard');

});*/
/*Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');


});*/
Route::post('/get_restaurant_info', 'RestaurantController@get_restaurants')->name('get_restaurants');
Route::post('/get_all_restaurant', 'RestaurantController@get_all_restaurant')->name('get_all_restaurant');
Route::post('/all_restaurants', 'RestaurantController@all_restaurant')->name('all_restaurant');
Route::post('/get_items', 'ItemController@get_items')->name('get_items');
Route::post('/get_area', 'AreaController@get_areas')->name('get_areas');
Route::post('/all_area', 'AreaController@all_areas')->name('all_areas');
Route::post('/get_restaurant_infos', 'RestaurantController@get_restaurant_info')->name('get_restaurant_infos');
//Route::get('/home', 'HomeController@index')->name('home');



/*Route::get('login/facebook', 'Auth\LoginController@redirectToProvider');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');*/

app/Offer.php
<?php

namespace App;
use Cviebrock\EloquentSluggable\Sluggable;

use Illuminate\Database\Eloquent\Model;

class Offer extends Model
{

    use Sluggable;
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'offer_name'
            ]
        ];
    }
  /*  public function shareafood(){
        return $this->hasMany('App\Shareafood');

    }*/
    public function shareafood(){
        return $this->hasMany('App\Shareafood');

    }
    public function restaurant(){
        return $this->belongsTo('App\restaurant');

    }
    public function area(){
        return $this->belongsTo('App\Area');

    }
    public function item(){
        return $this->belongsTo('App\Item');

    }

    public function offercomments()
    {
        return $this->hasMany('App\Offercomment');
    }
}

app/Http/Controllers/OfferController.php
<?php

namespace App\Http\Controllers;

use App\Offer;
use Illuminate\Http\Request;
use App\restaurant;
use App\Item;
use App\Area;
use Intervention\Image\ImageManagerStatic as Image;


class OfferController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function __construct()
    {
        $this->middleware('auth',['except' => ['index','show','offer_search','getSingle']]);
    }


    public function index()
    {
        $offers = Offer::all();


        return view('offer.index')->withoffers($offers);
    }
    public function offer_search()
    {
        $offers = Offer::all();


        return view('offer.search')->withoffers($offers);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $x = Area::all();
        $y = restaurant::all();
      //  $z = Item::all();
        $aa= \Auth::user()->restaurant->id;
        // dd($aa);
        $items= Item::all()->where('restaurant_id','==',$aa);
/*$ff=\Auth::user()->restaurant->area->area_name;
dd($ff);*/

        return view("offer.create")->withx($x)
                                   ->withy($y)
                                  /* ->withz($z)*/
                                    ->withitems($items);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(

            'offer_price'   => 'integer',

        ));

        $offer = new Offer();
        $offer->offer_name =$request->offer_name;
        $offer->offer_details =$request->offer_details;
        $offer->offer_duration_from =$request->offer_duration_from;
        $offer->offer_duration_to =$request->offer_duration_to;
        $offer->price =$request->offer_price;
        $offer->restaurant_id =\Auth::user()->restaurant->id;
        $offer->item_id =$request->item_name;
        $offer->area_id =\Auth::user()->restaurant->area->id;

        if ($request->hasFile('featured_img')) {
            $image = $request->file('featured_img');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $location = public_path('images/' . $filename);
            Image::make($image)->resize(800, 400)->save($location);

            $offer->offer_image = $filename;
        }

        $offer->save();
        session()->flash('success','It has been saved successfully');

        return redirect()->route('offer.index');
    }


    public function getSingle($slug) {
        //  dd($slug);
        //  return $slug;
        // fetch from the DB based on slug
        $offer = Offer::where('slug', '=', $slug)->first();
        // dd($reviews);

        // return the view and pass in the post object
        return view('offer.single')->withOffer($offer);
    }
    /**
     * Display the specified resource.
     *
     * @param  \App\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function show(Offer $offer)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function edit(Offer $offer)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Offer $offer)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Offer  $offer
     * @return \Illuminate\Http\Response
     */
    public function destroy(Offer $offer)
    {
        //
    }
}

resources/views/offer/create.blade.php
@extends('main')

@section('content')

    <div class="row">

        <section class="content center full-width">
            <div class="modal container">
                <h1 class="center">Create an Offer</h1>

                <form  method="POST" enctype="multipart/form-data" action="{{ route('offer.store') }}" {{--name="contactform" id="contactform"--}}>

                    <div id="message" class="alert alert-danger"></div>
                    <div class="f-row">

                        <label name="restaurant_name">Restaurant name:</label>
                        <input name="restaurant_name" id="restaurant_name" value="{{ \Auth::user()->restaurant->restaurant_name }}" class="form-control"readonly>
                    </div>


                    <div class="f-row">
                        <label name="item_name">Item name:</label>
                        <select name="item_name" id="item_name" class="form-control" required="">
                            <option value=""> -- Select One --</option>
                            @foreach ($items as $item_name)
                                <option value="{{ $item_name->id }}">{{ $item_name->item_name }}</option>
                            @endforeach
                        </select>

                    <div class="f-row">
                        <label name="area_name">Area name:</label>

                        <input type="text" name="area_name" id="area_name" value="{{ \Auth::user()->restaurant->area->area_name }}" class="form-control"readonly>
                    </div>

                    <div class="f-row">
                        <label name="offer_name">Offer Name:</label>
                        <input type="text" type="text" id="offer_name" name="offer_name" class="form-control" required="">
                    </div>

                    <div class="f-row">
                        <label name="offer_details">Offer details:</label>
                        <input type="text" id="offer_details" name="offer_details"  class="form-control" required="">
                    </div>
                    <div class="f-row">
                        <label name="offer_price">Offer price:</label>
                        <input type="text" id="offer_price" name="offer_price" class="form-control" required="">
                    </div>
                    <div class="f-row">
                        <label name="offer_duration">Offer duration:</label>
                        <div class="f-row">

                            <div >
                                <label name="offer_duration_from">From: </label>
                                <input id="offer_duration_from"  name="offer_duration_from" type="date" class="form-control">
                            </div>
                            <div >
                                <label name="offer_duration_to">To: </label>
                                <input id="offer_duration_to"  name="offer_duration_to" type="date" class="form-control">
                            </div>
                        </div>
                    </div>
                        <div class="f-row">
                            <label class="col-md-3 control-label" >image:</label>
                            <div class="col-md-8">
                                <input  type="file" id="featured_img" placeholder="offer_img" name="featured_img" class=""/>
                                <span class="required" id='spnFileError'></span>
                            </div>
                        </div>


                    <div class="f-row bwrap">
                        <input type="submit" value="Create an Offer" />
                    </div>
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                </form>
            </div>
        </section>
    </div>


    @endsection


{{--  <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h1>create an offer</h1>
            <hr>
            <form method="POST" action="{{ route('offer.store') }}">
                <div class="form-group">
                    <label name="restaurant_name">Restaurant name:</label>
                    <input name="restaurant_name" id="restaurant_name" value="{{ \Auth::user()->restaurant->restaurant_name }}" class="form-control"readonly>
                </div>
                <div class="form-group">
                    <label name="item_name">Item name:</label>
                    <select name="item_name" id="item_name" class="form-control">
                        <option value=""> -- Select One --</option>
                        @foreach ($items as $item_name)
                            <option value="{{ $item_name->id }}">{{ $item_name->item_name }}</option>
                        @endforeach
                    </select>
                </div>
                <div class="form-group">
                    <label name="area_name">Area name:</label>

                    <input name="area_name" id="area_name" value="{{ \Auth::user()->restaurant->area->area_name }}" class="form-control"readonly>


                </div>
                <div class="form-group">
                    <label name="offer_name">Offer Name:</label>
                    <input id="offer_name" name="offer_name" class="form-control">
                </div>
                <div class="form-group">
                    <label name="offer_details">Offer details:</label>
                    <input id="offer_details" name="offer_details" class="form-control">
                </div>
                <div class="form-group">
                    <label name="offer_price">Offer price:</label>
                    <input id="offer_price" name="offer_price" class="form-control">
                </div>
            <div class="form-group">
                <label name="offer_duration">Offer duration:</label>
                <div class="row">

                <div class="col-md-6 ">
                <input id="offer_duration_from" name="offer_duration_from" type="date" class="form-control">
                </div>
                    <div class="col-md-6 ">
                <input id="offer_duration_to" name="offer_duration_to" type="date" class="form-control">
                    </div>
                </div>
            </div>
                <div class="form-group">
                    <label for="exampleInputFile">File input</label>
                    <input type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
                    <small id="fileHelp" class="form-text text-muted"></small>
                </div>
                <input type="submit" value="give review" class="btn btn-success btn-lg btn-block">
                <input type="hidden" name="_token" value="{{ Session::token() }}">
            </form>
        </div>
    </div>﻿--}}

resources/views/offer/edit.blade.php
@extends('main')

@section('content')

    <form method="POST" action="{{ route('restaurant.update', $restaurant->id) }}">
        <div class="form-group">
            <label for="restaurant_name">restaurant_name:</label>
            <textarea type="text" class="form-control input-lg" id="restaurant_name" name="restaurant_name" rows="1" style="resize:none;">{{ $restaurant->restaurant_name }}</textarea>
        </div>
        <div class="form-group">
            <label for="address">address:</label>
            <textarea type="text" class="form-control input-lg" id="address" name="address" rows="10">{{ $restaurant->address }}</textarea>
        </div>

        <div class="col-md-4">
            <div class="well">
                <dl class="dl-horizontal">
                    <dt>Created at:</dt>
                    <dd>{{ date('M j, Y h:i:sa', strtotime($restaurant->created_at)) }}</dd>
                </dl>

                <dl class="dl-horizontal">
                    <dt>Last updated:</dt>
                    <dd>{{ date('M j, Y h:i:sa', strtotime($restaurant->updated_at)) }}</dd>
                </dl>
                <hr>
                <div class="row">
                    <div class="col-sm-6">
                        <a href="{{ route('restaurant.show', $restaurant->id) }}" class="btn btn-danger btn-block">Back</a>
                    </div>
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-success btn-block">Save</button>
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
        {{ method_field('PUT') }}

                    </div>
                </div>
            </div>
        </div>

    </form>﻿
    @endsection

resources/views/offer/search.blade.php
@extends('main')

@section('content')

    <div class="row">
        <div class="col-md-10">

            <h1>All Post</h1>
            <hr>
        </div>
        <div class="col-md-2">

            <a href="{{ route('offer.create') }}" class="button large">create offers</a>

        </div>

        <div class="row">
            <div class="col-md-12">
                <table class="table" id="offers">

                    <thead>
                    <th>#</th>
                    <th>restaurant name</th>
                    <th>item name</th>
                    <th>Area name</th>
                    <th>Offer Name</th>
                    <th>offer image</th>
                    <th>Offer details</th>
                    <th>Offer price</th>
                    <th>Offer duration from</th>
                    <th>Offer duration to</th>

                    </thead>
                    <tbody>
                    @foreach($offers as $offer)
                        <tr>
                            <th>{{$offer->id}}</th>
                            <td>{{$offer->restaurant->restaurant_name}}</td>
                            <td>{{$offer->item->item_name}}</td>
                            <td>{{$offer->area->area_name}}</td>
                            <td>{{$offer->offer_name}}</td>

                            @if ($offer->offer_image==null)  <td></td>
                            @else  <td><img src="{{asset('/images/'.$offer->offer_image)}}" alt="offer_image" height="200" width="200"></td>@endif
                            <td>{{$offer->offer_details}}</td>

                            <td>{{$offer->price}}</td>
                            <td>{{$offer->offer_duration_from}}</td>
                            <td>{{$offer->offer_duration_to}}</td>


                            {{--<td>{{str_limit($restaurant->address, 20)}}</td>
                            <td>{{date('M j, Y',strtotime($restaurant->created_at))}}</td>
                            <td>  <div class="row">
                                    <div class="col-sm-4">
                                        <a href="{{ route('restaurant.show', $restaurant->id) }}" class="btn btn-primary btn-block">Show</a>
                                    </div>
                                    <div class="col-sm-4">
                                        <a href="{{ route('restaurant.edit', $restaurant->id) }}" class="btn btn-primary btn-block">Edit</a>
                                    </div>
                                    <div class="col-sm-4">
                                        --}}{{----}}{{--   <a href="{{ route('restaurant.destroy', $restaurant->id) }}" class="btn btn-danger btn-block">Delete</a>--}}{{----}}{{--
                                        <form method="POST" action="{{ route('restaurant.destroy', $restaurant->id) }}">
                                            <input type="submit" value="Delete" class="btn btn-danger btn-block">
                                            <input type="hidden" name="_token" value="{{ Session::token() }}">
                                            {{ method_field('DELETE') }}
                                        </form>﻿
                                    </div>
                                </div>﻿</td>--}}
                        </tr>
                    @endforeach

                    </tbody>
                </table>


            </div>

        </div>

    </div>﻿

@endsection

@section('page_js')
    <script>
        $(function () {
            var table = $('#offers').DataTable(
                {
                    "pageLength": 50
                }
            )
        })

    </script>
@endsection

resources/views/offer/show.blade.php
@extends('main')

@section('content')

    <div class="row">
        <div class="col-md-8 ">
            <h1>{{$restaurant->restaurant_name}}</h1>
            <p class="form-control">{{$restaurant->address}} </p>
        </div>
    </div>﻿


        <div class="row">
            <div class="col-sm-4">
                <a href="{{ route('restaurant.edit', $restaurant->id) }}" class="btn btn-primary btn-block">Edit</a>
            </div>
            <div class="col-sm-4">
             {{--   <a href="{{ route('restaurant.destroy', $restaurant->id) }}" class="btn btn-danger btn-block">Delete</a>--}}
                <form method="POST" action="{{ route('restaurant.destroy', $restaurant->id) }}">
                    <input type="submit" value="Delete" class="btn btn-danger btn-block">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                    {{ method_field('DELETE') }}
                </form>﻿
            </div>
        </div>﻿







    @endsection

resources/views/offer/single.blade.php
@extends('main')


@section('content')

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
		{{--	@if(!empty($reviews->image))
				<img src="{{asset('/images/' . $post->image)}}" width="800" height="400" />
			@endif--}}
			<div class="row">
				<div class="col-md-12">
					<table class="table" {{--id="reviews"--}}>

						<thead>
						<th>#</th>
						<th>restaurant name</th>
						<th>item name</th>
						<th>Area name</th>
						<th>Offer Name</th>
						<th>offer image</th>
						<th>Offer details</th>
						<th>Offer price</th>
						<th>Offer duration from</th>
						<th>Offer duration to</th>


						</thead>
						<tbody>

							<tr>

								<th>{{$offer->id}}</th>
								<td>{{$offer->restaurant->restaurant_name}}</td>
								<td>{{$offer->item->item_name}}</td>
								<td>{{$offer->area->area_name}}</td>
								<td>{{$offer->offer_name}}</td>
								@if ($offer->offer_image==null)  <td></td>
								@else  <td><img src="{{asset('/images/'.$offer->offer_image)}}" alt="offer_image" height="150px" width="250px"></td>@endif
								<td>{{$offer->offer_details}}</td>
								<td>{{$offer->price}}</td>
								<td>{{$offer->offer_duration_from}}</td>
								<td>{{$offer->offer_duration_to}}</td>



                            </tr>


</tbody>
        </table>


    </div>

</div>


			{{--<p>{!! $post->body !!}</p>
			<hr>
			<p>Posted In: {{ $post->category->name }}</p>--}}
		</div>
	</div>


	<div class="comments" id="comments">
		<h2>{{ $offer->offercomments()->count() }} Comments </h2>
		@foreach($offer->offercomments as $comment)
			{{--
                        {{dd($comment->user['user_image'])}}
            --}}
			<ol class="comment-list">


				<!--comment-->
				<li class="comment depth-1">
					<div class="avatar"><a href="my_profile.html"><img src="{{asset('images/'.$comment->user['user_image'])}}" alt="" /></a></div>
					<div class="comment-box" style="text-align: left">
						<div class="comment-author meta">
							Name:	<strong>{{ $comment->name}}</strong> {{ date('F dS, Y - g:iA' ,strtotime($comment->created_at)) }}{{-- <a href="#" class="comment-reply-link"> Reply</a>--}}
						</div>
						<div class="comment-text">
							{{ $comment->comment }}
						</div>
					</div>
				</li>
				<!--//comment-->
			</ol>
		@endforeach
	</div>


{{--
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h3 class="comments-title"><span class="glyphicon glyphicon-comment"></span>  {{ $offer->offercomments()->count() }} Comments</h3>
			@foreach($offer->offercomments as $comment)
				<div class="comment">
					<div class="author-info">

						--}}
{{--<img src="{{ "https://www.gravatar.com/avatar/" . md5(strtolower(trim($comment->email))) . "?s=50&d=monsterid" }}" class="author-image">--}}{{--

						<div class="author-name">

							<h4>{{ $comment->name}}</h4>
							<p class="author-time">{{ date('F dS, Y - g:iA' ,strtotime($comment->created_at)) }}</p>
						</div>

					</div>

					<div class="comment-content">
						{{ $comment->comment }}
					</div>

				</div>
			@endforeach
		</div>
	</div>
--}}


	{{--<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<h3 class="comments-title"><span class="glyphicon glyphicon-comment"></span>  {{ $post->comments()->count() }} Comments</h3>
			@foreach($post->comments as $comment)
				<div class="comment">
					<div class="author-info">

						<img src="{{ "https://www.gravatar.com/avatar/" . md5(strtolower(trim($comment->email))) . "?s=50&d=monsterid" }}" class="author-image">
						<div class="author-name">
							<h4>{{ $comment->name }}</h4>
							<p class="author-time">{{ date('F dS, Y - g:iA' ,strtotime($comment->created_at)) }}</p>
						</div>

					</div>

					<div class="comment-content">
						{{ $comment->comment }}
					</div>

				</div>
			@endforeach
		</div>
	</div>--}}
	<div class="comment-respond" id="respond">
		<h2>Leave a reply</h2>
		<div class="container">
			<p><strong>Note:</strong> Comments on the web site reflect the views of their authors, and not necessarily the views of the BdFoodReview internet portal. Requested to refrain from insults, swearing and vulgar expression. We reserve the right to delete any comment without notice explanations.</p>
			<form method="POST" action="{{ route('offercomments.store') }}">
				<div class="f-row">
					<div class="third">
						<input type="text"  name="name" id="name" placeholder="Your name" />
						<span class="req">*</span>
					</div>

					<div class="form-group">
						<input type="hidden" class="form-control" value="{{$offer->id}}" name="offer_id" id="{{$offer->id}}">

					</div>

				</div>
				<div class="f-row">
					<textarea name="comment" id="comment"></textarea>
				</div>

				<div class="f-row">
					<div class="third bwrap" style="padding-bottom: 40px">
						<input type="submit" value="Submit comment" />
					</div>
				</div>


				{{ csrf_field() }}
			</form>
		</div>
	</div>


{{--
		<div class="row">
			<form method="POST" class="col-md-8 col-md-offset-2" style="margin-top: 50px;" action="{{ route('offercomments.store') }}">
				--}}
{{--<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<input type="text" class="form-control" name="Name" autocomplete="off" id="Name" placeholder="Name">
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<input type="email" class="form-control" name="email" autocomplete="off" id="email" placeholder="E-mail">
						</div>
					</div>
				</div>--}}{{--

				<div class="row">
				<div class="col-md-6">
					<label name="comment">User Name:</label>
					<div class="form-group">
						<input type="text" class="form-control"  name="name" id="name">
					</div>
				</div>
				</div>
				--}}
{{--<div class="col-md-6">--}}{{--

					<div class="form-group">
						<input type="hidden" class="form-control" value="{{$offer->id}}" name="offer_id" id="{{$offer->id}}">
					</div>
			--}}
{{--	</div>--}}{{--


				<div class="row">
					<div class="col-md-12">
						<label name="comment">comment:</label>
						<div class="form-group">
							<textarea class="form-control textarea" rows="3" name="comment" id="comment" placeholder="comment"></textarea>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-md-12">
						<button type="submit" class="btn main-btn pull-right">comment</button>
					</div>
				</div>
				{{ csrf_field() }}
			</form>
		</div>
--}}

@endsection
			{{--<dl class="dl-horizontal">
				<label>Url:</label>
				<p><a href="{{ route('blog.single', $post->slug) }}">{{ route('blog.single', $post->slug) }}</a></p>
			</dl>--}}
		{{--<div id="comment-form" class="col-md-8 col-md-offset-2" style="margin-top: 50px;">
			{{ Form::open(['route' => ['reviewcomments.store'/*, $reviews->id*/], 'method' => 'POST']) }}

				<div class="row">

					<div class="col-md-6">
						{{ Form::label('review_id', "review_id:") }}
						{{ Form::text('review_id', null, ['class' => 'form-control']) }}
					</div>
				--}}{{--
					<div class="col-md-6">
						{{ Form::label('email', 'Email:') }}
						{{ Form::text('email', null, ['class' => 'form-control']) }}
					</div>--}}{{--

					<div class="col-md-12">
						{{ Form::label('comment', "Comment:") }}
						{{ Form::textarea('comment', null, ['class' => 'form-control', 'rows' => '5']) }}

						{{ Form::submit('Add Comment', ['class' => 'btn btn-success btn-block', 'style' => 'margin-top:15px;']) }}
					</div>
				</div>

			{{ Form::close() }}
		</div>--}}