routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('pages.home');
});*/

Route::get('/vue', function () {
    return view('welcome');
});

Route::get('/','HomeController@index');
Route::get('/home','HomeController@index');
Route::post('/gg', 'ItemController@gg');

Route::get('/contact', 'HomeController@contact');
Route::get('/about', 'HomeController@about');

//Route::get('/review','PostsController@show_review');
//Route::get('/write_a_review','PostsController@write_a_review')->middleware('auth');
/*Route::get('/offers','PostsController@offers');*/
/*Route::get('/share_a_food','ShareafoodController@share_a_food')->middleware('auth');*/
Route::get('/foodgraphy','PostsController@foodgraphy');
Route::get('/map','MapController@index');
Route::get('/item/all','ItemController@allitem');

Route::get('/owners/all','HomeController@owners');


Route::get('/restaurant/all','RestaurantController@allrestaurant');


Route::get('/offer/search','OfferController@offer_search')->name('offer.search');
Route::get('/shareafood/search','ShareafoodController@shareafood_search')->name('shareafood.search');
Route::get('/reviews/search','ReviewsController@reviews_search')->name('reviews.search');






Route::get('reviews/tag/{slug}', 'ReviewsController@getSingle')->name('reviews.single')/*->where('slug', '[\w\d\-\_]+')*/;
Route::get('offer/tag/{slug}', 'OfferController@getSingle')->name('offer.single')/*->where('slug', '[\w\d\-\_]+')*/;
Route::get('shareafood/tag/{slug}', 'ShareafoodController@getSingle')->name('shareafood.single')/*->where('slug', '[\w\d\-\_]+')*/;
Route::get('restaurant/tag/{slug}', 'RestaurantController@getSingle')->name('restaurant.single');
Route::get('item/tag/{slug}', 'ItemController@getSingle')->name('item.single');


/*
Route::group(['middleware' => ['auth']], function () {



});*/

Route::resource('post','PostsController');
Route::resource('restaurant','RestaurantController');
Route::resource('item','ItemController');
Route::resource('shareafood','ShareafoodController');
Route::resource('reviews','ReviewsController');
Route::resource('area','AreaController');
Route::resource('offer','OfferController');
Route::resource('users','UserController');

Route::resource('reviewcomments','ReviewcommentController');
Route::resource('offercomments','OffercommentController');
Route::resource('shareafoodcomments','ShareafoodcommentController');


//Route::post('reviews/{slug}', ['as' => 'reviews.single', 'uses' => 'ReviewsController@store'])->where('slug', '[\w\d\-\_]+');




/*
Route::get('/admin_review','AdminController@show_review');
Route::get('/admin_write_a_review','AdminController@write_a_review');
Route::get('/admin_offers','AdminController@offers');
Route::get('/admin_share_a_food','AdminController@share_a_food');
Route::get('/admin_foodgraphy','AdminController@foodgraphy');
Route::get('/admin_home','AdminController@index');*/
Route::get('/admin_create','AdminController@create_pages');




Auth::routes();

/*Route::prefix('admin')->group(function (){
    Route::get('/login','/Auth/AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login','/Auth/AdminLoginController@login')->name('admin.login.submit');
    Route::get('/','AdminController@index')->name('admin.dashboard');

});*/
/*Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');


});*/
Route::post('/get_restaurant_info', 'RestaurantController@get_restaurants')->name('get_restaurants');
Route::post('/get_all_restaurant', 'RestaurantController@get_all_restaurant')->name('get_all_restaurant');
Route::post('/all_restaurants', 'RestaurantController@all_restaurant')->name('all_restaurant');
Route::post('/get_items', 'ItemController@get_items')->name('get_items');
Route::post('/get_area', 'AreaController@get_areas')->name('get_areas');
Route::post('/all_area', 'AreaController@all_areas')->name('all_areas');
Route::post('/get_restaurant_infos', 'RestaurantController@get_restaurant_info')->name('get_restaurant_infos');
//Route::get('/home', 'HomeController@index')->name('home');



/*Route::get('login/facebook', 'Auth\LoginController@redirectToProvider');
Route::get('login/facebook/callback', 'Auth\LoginController@handleProviderCallback');*/

app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Cviebrock\EloquentSluggable\Sluggable;


class Item extends Model
{

    use Sluggable;
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'item_name'
            ]
        ];
    }

    protected $table = 'items';
    public function restaurant(){

        return $this->belongsTo('App\restaurant');
    }
    public function review(){

        return $this->hasMany('App\reviews');
    }
    public function shareafood(){

        return $this->hasMany('App\Shareafood');
    }
    public function offer(){

        return $this->hasMany('App\Offer');
    }



  /*  public function item_restaurant(){
        return $this->hasMany('App\ItemRestaurant','item_id','id');

    }*/

}

app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Area;
use App\Item;
use Illuminate\Http\Request;
use App\restaurant;
use App\User;
use App\ItemRestaurant;
use Intervention\Image\ImageManagerStatic as Image;
class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
       // dd($aa);
      //  $items = Item::all();
      /*  if(\Auth::user()->restaurant==null)
        {$x = restaurant::all();
            return view('items.create')->withx($x);}*/

        if(\Auth::user()->restaurant==null)
        {    $x = Area::all();

            $y = \Auth::user();

            return view("restaurant.create")->withx($x)
                ->withy($y);}


        else
        {
            $aa= \Auth::user()->restaurant->id;
           // dd($aa);
            $items= Item::all()->where('restaurant_id','==',$aa);
          //  dd($items->item_name);
            /*$items=\Auth::user()->item;
            $aa= \Auth::user()->id;*/
         //   dd($items);
            return view('items.index')->withitems($items);}



        }
    public function allitem()
    {
        // dd($aa);
          $items = Item::all();

        return view('items.allitem')->withItems($items);



    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {  $x = restaurant::all();
        return view('items.create')->withx($x);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, array(

            'price'   => 'integer',

        ));

      //  dd($request->all());
        $items = new item;
        $items->item_name =$request->item_name;
       /* $items->restaurant_id =$request->restaurant_name;*/
        $items->restaurant_id =\Auth::user()->restaurant->id;
        $items->price =$request->price;

        if ($request->hasFile('featured_img')) {
            $image = $request->file('featured_img');
            $filename = time() . '.' . $image->getClientOriginalExtension();
            $location = public_path('images/' . $filename);
            Image::make($image)->resize(800, 400)->save($location);

            $items->item_image = $filename;
        }

     //  dd($items);
        $items->save();
        session()->flash('success','It has been saved successfully!');

        return redirect()->route('item.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $item = Item::find($id);
        return view('items.show')->withitem($item);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
       // dd($request->all());

    }

    public function gg(Request $request)
    {
      //  dd($request->ff);
       // $item = Item::find($id);
//dd($item);
        $item = Item::find($request->ff);

       $a=$item->id;
       $item->owners_recommendation = 1;
        $item->update();
  // dd($b);
       // $item->owners_recommendation = 1;
      //  $kk=Item::all()->except($request->ff);
        //$kk->owners_recommendation = 0;

        $b= $item->id;
        $aa= \Auth::user()->id;
      // dd($aa);
      $cc= Item::where('restaurant_id','=',$aa)->where('id','!=',$b)->update(['owners_recommendation' => 0]);
      // dd($cc);


        //Item::where('id','!=',$b)->update(['owners_recommendation' => 0]);
     /*   $item->update();*/


       // $kk->save();

        return redirect()->back()->with('message', 'recommendation updated');
    }



    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        //
    }

    public function getSingle($slug) {
        //  dd($slug);
        //  return $slug;
        // fetch from the DB based on slug
        $item = Item::where('slug', '=', $slug)->first();
        //dd($item);

        // return the view and pass in the post object
        return view('items.single')->withItem($item);
    }

    public function get_items(Request $request){
//        dd($request);
        $items = Item::all()->pluck('item_name','id')->toArray();
        return response()->json([json_encode([$items])]);
    }
}

resources/views/items/allitem.blade.php
@extends('main')

@section('content')

    <div class="row">
       <div class="col-md-10">

           <h1>All Items</h1>

       </div>


<div class="row">
    <div class="col-md-12">
        <table class="table" id="items">

            <thead>
            <th>Items name</th>


            <th>item image</th>

            <th>Restaurant name</th>
            <th>Price</th>


            </thead>
<tbody>
  @foreach($items as $item)
<tr>
    <td>{{$item->item_name}}</td>
@if ($item->item_image==null)  <td></td>
  @else  <td><img src="{{asset('/images/'.$item->item_image)}}" alt="item_image" height="200" width="200"></td>@endif

    <td>{{$item->restaurant->restaurant_name}}</td>

    <td>{{$item->price}}</td>

  {{--  <td>{{$item->owners_recommendation}}</td>--}}



    {{--<td>{{str_limit($restaurant->address, 20)}}</td>
    <td>{{date('M j, Y',strtotime($restaurant->created_at))}}</td>
    <td>  <div class="row">
            <div class="col-sm-4">
                <a href="{{ route('restaurant.show', $restaurant->id) }}" class="btn btn-primary btn-block">Show</a>
            </div>
            <div class="col-sm-4">
                <a href="{{ route('restaurant.edit', $restaurant->id) }}" class="btn btn-primary btn-block">Edit</a>
            </div>
            <div class="col-sm-4">
                --}}{{--   <a href="{{ route('restaurant.destroy', $restaurant->id) }}" class="btn btn-danger btn-block">Delete</a>--}}{{--
                <form method="POST" action="{{ route('restaurant.destroy', $restaurant->id) }}">
                    <input type="submit" value="Delete" class="btn btn-danger btn-block">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                    {{ method_field('DELETE') }}
                </form>﻿
            </div>
        </div>﻿</td>--}}
</tr>
@endforeach

</tbody>
        </table>


    </div>

</div>

    </div>﻿

    @endsection

@section('page_js')
    <script>
        $(function () {
            var table = $('#items').DataTable(
                {
                    "pageLength": 50
                }
            )
        })

    </script>
@endsection

resources/views/items/create.blade.php
@extends('main')

@section('content')
    <div class="row">
        <!--content-->
        <section class="content center full-width">
            <div class="modal container">
                <form  method="POST" enctype="multipart/form-data" action="{{ route('item.store') }}" {{--name="contactform" id="contactform"--}}>
                    <h1 class="center">Create an Item</h1>
                    <div id="message" class="alert alert-danger"></div>
                    <div class="f-row">
                        <label name="item_name">Item Name:</label>
                        <input type="text" id="item_name" name="item_name" class="form-control" required="">
                    </div>

                    <div class="f-row">
                        <label name="price">Price:</label>
                        <input type="text" id="price" name="price" class="form-control" required="">
                    </div>


                    <div class="f-row">
                        <label class="col-md-3 control-label" >image:</label>
                        <div class="col-md-8">
                            <input  type="file" id="featured_img" placeholder="featured_img" name="featured_img" class=""/>
                            <span class="required" id='spnFileError'></span>
                        </div>
                    </div>



                    <div class="f-row bwrap">
                        <input type="submit" value="Insert Item" />
                    </div>
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                </form>
            </div>
        </section>
        <!--//content-->
    </div>



    @endsection

{{--
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <h1>Item input</h1>
        <hr>
        <form method="POST" action="{{ route('item.store') }}">
            <div class="form-group">
                <label name="item_name">Item Name:</label>
                <input id="item_name" name="item_name" class="form-control">
            </div>

            <div class="form-group">
                <label name="price">Price:</label>
                <input id="price" name="price" class="form-control">
            </div>


            --}}
{{--   <div class="form-group">
                   <label name="active">Owners recomendation:</label>
                   <select name="active">
                       <option value="yes" id="active" class="form-control">yes</option>
                       <option value="no" id="active" class="form-control">no</option>
                   </select>
               </div>--}}{{--




            --}}
{{--  <div class="form-group">
                  <label name="restaurant_name">Restaurant name:</label>
                  <select name="restaurant_name" id="restaurant_name" class="form-control">
                      <option value=""> -- Select One --</option>
                      @foreach ($x as $restaurant_name)
                          <option value="{{ $restaurant_name->id }}">{{ $restaurant_name->restaurant_name }}</option>
                      @endforeach
                  </select>
              </div>--}}{{--


            <div class="form-group">
                <label for="exampleInputFile">File input</label>
                <input type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
                <small id="fileHelp" class="form-text text-muted"></small>
            </div>



            <input type="submit" value="give review" class="btn btn-success btn-lg btn-block">
            <input type="hidden" name="_token" value="{{ Session::token() }}">
        </form>
    </div>
</div>﻿--}}

resources/views/items/edit.blade.php
@extends('main')

@section('content')

    <form method="POST" action="{{ route('restaurant.update', $restaurant->id) }}">
        <div class="form-group">
            <label for="restaurant_name">restaurant_name:</label>
            <textarea type="text" class="form-control input-lg" id="restaurant_name" name="restaurant_name" rows="1" style="resize:none;">{{ $restaurant->restaurant_name }}</textarea>
        </div>
        <div class="form-group">
            <label for="address">address:</label>
            <textarea type="text" class="form-control input-lg" id="address" name="address" rows="10">{{ $restaurant->address }}</textarea>
        </div>

        <div class="col-md-4">
            <div class="well">
                <dl class="dl-horizontal">
                    <dt>Created at:</dt>
                    <dd>{{ date('M j, Y h:i:sa', strtotime($restaurant->created_at)) }}</dd>
                </dl>

                <dl class="dl-horizontal">
                    <dt>Last updated:</dt>
                    <dd>{{ date('M j, Y h:i:sa', strtotime($restaurant->updated_at)) }}</dd>
                </dl>
                <hr>
                <div class="row">
                    <div class="col-sm-6">
                        <a href="{{ route('restaurant.show', $restaurant->id) }}" class="btn btn-danger btn-block">Back</a>
                    </div>
                    <div class="col-sm-6">
                        <button type="submit" class="btn btn-success btn-block">Save</button>
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
        {{ method_field('PUT') }}

                    </div>
                </div>
            </div>
        </div>

    </form>﻿
    @endsection

resources/views/items/index.blade.php
@extends('main')

@section('content')

    <div class="row">
       <div class="col-md-10">

           <h1>All Items</h1>

       </div>
        <div class="col-md-2">

            <a href="{{ route('item.create') }}" class="button large">Add an item</a>

        </div>

<div class="row">
    <div class="col-md-12">
        <table class="table" id="items">

            <thead>
            <th>Items name</th>


            <th>item image</th>

            <th>Restaurant name</th>
            <th>Price</th>
            <th>owner's recommended</th>


            </thead>
<tbody>
  @foreach($items as $item)
<tr>
    <td>{{$item->item_name}}</td>
@if ($item->item_image==null)  <td></td>
  @else  <td><img src="{{asset('/images/'.$item->item_image)}}" alt="item_image" height="200" width="200"></td>@endif

    <td>{{$item->restaurant->restaurant_name}}</td>

    <td>{{$item->price}}</td>

  {{--  <td>{{$item->owners_recommendation}}</td>--}}

<td>
    <form method="post" action="/gg">
        <input type="hidden" name="ff" value="{{$item->id}}"/>
        <button class="{{--btn btn-lg btn-success--}}@if(!$item->owners_recommendation)  button white @endif" type="submit">
          @if(!$item->owners_recommendation) recommend this
            @else owners recommended  @endif
        </button>

    </form>

</td>

    {{--<td>{{str_limit($restaurant->address, 20)}}</td>
    <td>{{date('M j, Y',strtotime($restaurant->created_at))}}</td>
    <td>  <div class="row">
            <div class="col-sm-4">
                <a href="{{ route('restaurant.show', $restaurant->id) }}" class="btn btn-primary btn-block">Show</a>
            </div>
            <div class="col-sm-4">
                <a href="{{ route('restaurant.edit', $restaurant->id) }}" class="btn btn-primary btn-block">Edit</a>
            </div>
            <div class="col-sm-4">
                --}}{{--   <a href="{{ route('restaurant.destroy', $restaurant->id) }}" class="btn btn-danger btn-block">Delete</a>--}}{{--
                <form method="POST" action="{{ route('restaurant.destroy', $restaurant->id) }}">
                    <input type="submit" value="Delete" class="btn btn-danger btn-block">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                    {{ method_field('DELETE') }}
                </form>﻿
            </div>
        </div>﻿</td>--}}
</tr>
@endforeach

</tbody>
        </table>


    </div>

</div>

    </div>﻿

    @endsection

@section('page_js')
    <script>
        $(function () {
            var table = $('#items').DataTable(
                {
                    "pageLength": 50
                }
            )
        })

    </script>
@endsection

resources/views/items/recommendindex.blade.php
@extends('main')

@section('content')



<div class="row">
    <div class="col-md-12">
        <table class="table" id="items">

            <thead>
            <th>Items name</th>


            <th>item image</th>

{{--
            <th>Restaurant name</th>
--}}
            <th>Price</th>


            </thead>
<tbody>
  @foreach($recomendation_single as $item)
<tr>
    <td>{{$item['item_name']}}</td>
    @if ($item['item_image']==null)  <td>{{--<img src="{{asset('images/no.jpg')}}"height="200" width="270" alt="image">--}}</td>
    @else  <td><img src="{{asset('/images/'.$item['item_image'])}}" alt="item_image" height="150px" width="250px"></td>@endif

 {{--   <td>{{$item->restaurant->restaurant_name}}</td>--}}

    <td>{{$item['price']}}</td>

  {{--  <td>{{$item->owners_recommendation}}</td>--}}



    {{--<td>{{str_limit($restaurant->address, 20)}}</td>
    <td>{{date('M j, Y',strtotime($restaurant->created_at))}}</td>
    <td>  <div class="row">
            <div class="col-sm-4">
                <a href="{{ route('restaurant.show', $restaurant->id) }}" class="btn btn-primary btn-block">Show</a>
            </div>
            <div class="col-sm-4">
                <a href="{{ route('restaurant.edit', $restaurant->id) }}" class="btn btn-primary btn-block">Edit</a>
            </div>
            <div class="col-sm-4">
                --}}{{--   <a href="{{ route('restaurant.destroy', $restaurant->id) }}" class="btn btn-danger btn-block">Delete</a>--}}{{--
                <form method="POST" action="{{ route('restaurant.destroy', $restaurant->id) }}">
                    <input type="submit" value="Delete" class="btn btn-danger btn-block">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                    {{ method_field('DELETE') }}
                </form>﻿
            </div>
        </div>﻿</td>--}}
</tr>
@endforeach

</tbody>
        </table>


    </div>

</div>



    @endsection

@section('page_js')
    <script>
        $(function () {
            var table = $('#items').DataTable(
                {
                    "pageLength": 50
                }
            )
        })

    </script>
@endsection

resources/views/items/show.blade.php
@extends('main')

@section('content')

    <div class="row">
        <div class="col-md-8 ">
            <h1>{{$item->item_name}}</h1>
            <p class="form-control">{{$item->price}} </p>
        </div>
    </div>﻿


        <div class="row">
            <div class="col-sm-4">
                <a href="{{ route('item.edit', $item->id) }}" class="btn btn-primary btn-block">Edit</a>
            </div>
            <div class="col-sm-4">
             {{--   <a href="{{ route('restaurant.destroy', $restaurant->id) }}" class="btn btn-danger btn-block">Delete</a>--}}
                <form method="POST" action="{{ route('item.destroy', $item->id) }}">
                    <input type="submit" value="Delete" class="btn btn-danger btn-block">
                    <input type="hidden" name="_token" value="{{ Session::token() }}">
                    {{ method_field('DELETE') }}
                </form>﻿
            </div>
        </div>﻿







    @endsection

resources/views/items/single.blade.php
@extends('main')



@section('content')

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
		{{--	@if(!empty($reviews->image))
				<img src="{{asset('/images/' . $post->image)}}" width="800" height="400" />
			@endif--}}
			<div class="row">
				<div class="col-md-12">
					<table class="table" id="reviews">

						<thead>
{{--
						<th>#</th>
--}}
						<th>Items name</th>


						<th>item image</th>

						<th>Restaurant name</th>
						<th>Price</th>
{{--
						<th>owner's recommended</th>
--}}


						</thead>
						<tbody>

							<tr>

{{--
								<td>{{$item->id}}</td>
--}}
								<td>{{$item->item_name}}</td>
								@if ($item->item_image==null)  <td></td>
								@else  <td><img src="{{asset('/images/'.$item->item_image)}}" alt="item_image" height="200" width="200"></td>@endif

								<td>{{$item->restaurant->restaurant_name}}</td>

								<td>{{$item->price}}</td>



                            </tr>


</tbody>
        </table>


    </div>

</div>


			{{--<p>{!! $post->body !!}</p>
			<hr>
			<p>Posted In: {{ $post->category->name }}</p>--}}
		</div>
	</div>












@endsection